android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
kotlin.code.style=official
kotlin.incremental=true
android.nonTransitiveRClass=true
android.nonFinalResIds=false
org.gradle.configuration-cache=false
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64
